name: "Style Lint"

on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths:
      - "_sass/**/*.scss"
  pull_request:
    paths:
      - "_sass/**/*.scss"

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
      - run: npm i
      - run: npm test
